// SHINE App — Sample Data
// This file is loaded as a regular script (window.SHINE_SAMPLE) so the app
// works when opened via file:// without a server. Real reviews replace this
// by importing a findings.json (File > Import).

window.SHINE_SAMPLE = {
  reviews_index: [
    {
      review_id: "AAA-COINV-A-FY2025-D1.1",
      fund_code: "AAA-COINV-A",
      fund_family: "AAA Coinvest",
      fund_legal_name: "AAA Coinvest Fund A LP",
      period: "FY2025",
      draft: "Draft 1.1",
      reviewer: "ashinde@apollo.com",
      review_date: "2026-05-17",
      last_touched: 1747497600000, // 2026-05-17
      readiness: "NOT_READY",
      finding_count: 16,
      coverage_pct: 0.96,
      open_critical: 3,
      prior_draft_delta: { new: 2, resolved: 1 }
    },
    {
      review_id: "AAA-COINV-B-FY2025-D1.0",
      fund_code: "AAA-COINV-B",
      fund_family: "AAA Coinvest",
      fund_legal_name: "AAA Coinvest Fund B LP",
      period: "FY2025",
      draft: "Draft 1.0",
      reviewer: "ashinde@apollo.com",
      review_date: "2026-05-14",
      last_touched: 1747238400000,
      readiness: "READY_WITH_EXCEPTIONS",
      finding_count: 7,
      coverage_pct: 0.92,
      open_critical: 0,
      prior_draft_delta: null
    },
    {
      review_id: "AAA-CREDIT-III-Q1-D2.0",
      fund_code: "AAA-CREDIT-III",
      fund_family: "AAA Direct Credit",
      fund_legal_name: "AAA Direct Credit Fund III LP",
      period: "Q1-2026",
      draft: "Draft 2.0",
      reviewer: "ashinde@apollo.com",
      review_date: "2026-05-09",
      last_touched: 1746806400000,
      readiness: "READY",
      finding_count: 3,
      coverage_pct: 0.98,
      open_critical: 0,
      prior_draft_delta: { new: 0, resolved: 4 }
    }
  ],

  // Full review payload for the primary demo
  review: {
    brief: {
      review_id: "AAA-COINV-A-FY2025-D1.1",
      fund_code: "AAA-COINV-A",
      fund_legal_name: "AAA Coinvest Fund A LP",
      domicile: "Cayman Islands",
      structure_type: "Closed-end PE LP",
      period: "FY2025",
      draft: "Draft 1.1",
      fiscal_year_end: "12-31",
      regulatory_jurisdictions: ["CIMA", "SEC", "IRS"],
      presentation: "US GAAP / ASC 946",
      materiality_planning_pct: 0.0075,
      materiality_planning_value: 18750000,
      clearly_trivial_value: 937500,
      total_nav: 2500000000,
      reviewer: "ashinde@apollo.com",
      review_date: "2026-05-17",
      build_date: "2026-05-17"
    },

    coverage: {
      subagents_completed: ["mechanical", "narrative", "standards", "comparative", "defense"],
      subagents_failed: [],
      layers_covered: ["L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8", "L9", "L10", "L11", "L12", "L13", "L14"],
      layers_skipped: [],
      asc_paragraphs_applicable_count: 47,
      asc_paragraphs_checked_count: 45,
      asc_paragraphs_skipped_with_reason: [
        { paragraph: "ASC 815-10-50-4D", reason_code: "SUBPOPULATION_ABSENT", reason: "No netting positions on BS" },
        { paragraph: "ASC 205-40-50-1", reason_code: "NOT_APPLICABLE", reason: "Fund within investment period; no going-concern doubt conditions" }
      ],
      coverage_completeness_pct: 0.96,
      regulatory_citations_referenced: ["CIMA:PFA", "CIMA:MFA-AUDIT", "SEC:RULE-206-4-2", "IRS:PFIC"],
      regulatory_corpus_attestation_age_days: { CIMA: 14, SEC: 14, IRS: 14 },
      subagent_elapsed_seconds: { mechanical: 142, narrative: 98, standards: 168, comparative: 112, defense: 96 },
      subagent_timeouts_fired: [],
      schema_rejections: { total: 0, by_subagent: {} },
      degradation_chips: []
    },

    findings: [
      {
        id: "F-001",
        subagent: "orchestrator",
        layer: "L0",
        statement: "Cover",
        section: "Cover page",
        sortOrder: 1,
        location: { statement: "Cover", page: 1, line_id: "Domicile statement", note_ref: null, column: null, xlsx_cell: null },
        severity: { impact: "CRITICAL", confidence: "CERTAIN" },
        subagentRaw: "Cover page lists domicile as Delaware. Fund metadata records domicile as Cayman Islands. Qualitative materiality applies — this is CRITICAL regardless of dollar impact.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Confirm correct domicile with fund formation documents; correct the cover page (and any internal references) before issuance.",
        fixSubagentRaw: "Confirm correct domicile with fund formation documents; correct the cover page (and any internal references) before issuance.",
        fixVoiceNormalized: null,
        fixControllerEdited: null,
        evidence: { quoted_text: "AAA Coinvest Fund A LP, a Delaware limited partnership", asc_reference: null, regulatory_citation: null },
        merge_key: "Cover::Cover page::Domicile statement::language_error",
        finding_class: "language_error",
        prior_review_recurrence: "NEW",
        evergreen_accepted: false,
        evergreen_acceptance_reason: null,
        evergreen_acceptance_date: null,
        reconciler_pattern: null,
        reconciler_specificity_score: null,
        constituent_findings: [],
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "asc-matrices.md": "8.1.0" },
        state: "OPEN",
        disposition_notes: null,
        discard_attestation: null,
        detail: null
      },
      {
        id: "F-002",
        subagent: "standards",
        layer: "L9",
        statement: "Statement of Assets and Liabilities",
        section: "Investments at fair value",
        sortOrder: 5,
        location: { statement: "Statement of Assets and Liabilities", page: 3, line_id: "Investments at fair value", note_ref: null, column: "Current period", xlsx_cell: null },
        severity: { impact: "HIGH", confidence: "CERTAIN" },
        subagentRaw: "The Statement of Assets and Liabilities omits the parallel cost column for investments. ASC 946-210-45-1 requires both cost and fair value when the fund holds investments measured at fair value.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Add a 'Cost' column adjacent to 'Fair value' for investments, with the corresponding aggregate cost figure tied to the Schedule of Investments.",
        fixSubagentRaw: "Add a 'Cost' column adjacent to 'Fair value' for investments, with the corresponding aggregate cost figure tied to the Schedule of Investments.",
        fixVoiceNormalized: null,
        fixControllerEdited: null,
        evidence: { asc_reference: "ASC 946-210-45-1", quoted_text: "Investments at fair value $ 2,184,500,000", regulatory_citation: null },
        merge_key: "Statement of Assets and Liabilities::Investments at fair value::Investments at fair value::asc_mapping_gap",
        finding_class: "asc_mapping_gap",
        prior_review_recurrence: "NEW",
        evergreen_accepted: false,
        reconciler_pattern: null,
        reconciler_specificity_score: null,
        constituent_findings: [],
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "asc-matrices.md": "8.1.0" },
        state: "OPEN",
        disposition_notes: null,
        detail: null
      },
      {
        id: "F-003",
        subagent: "mechanical",
        layer: "L2",
        statement: "Statement of Operations",
        section: "Realized and unrealized gain/loss",
        sortOrder: 10,
        location: { statement: "Statement of Operations", page: 4, line_id: "Net realized and unrealized gain/loss", note_ref: null, column: "Current period", xlsx_cell: "SOO!C28" },
        severity: { impact: "HIGH", confidence: "CERTAIN" },
        subagentRaw: "The Statement of Operations presents 'Net realized and unrealized gain/loss on investments' as a single line ($142.3M). Realized vs unrealized bifurcation is absent. The workbook source (SOO tab, cells C26 and C27) shows realized $61.2M and unrealized $81.1M — bifurcation is available but not presented.",
        voiceNormalized: null,
        controllerEdited: "Realized vs unrealized gain/loss on investments is combined into a single line ($142.3M). Bifurcation is required and available — split into Realized $61.2M and Unrealized $81.1M.",
        fix: "Bifurcate the combined line on the face of the Statement of Operations: 'Net realized gain (loss) on investments' and 'Net change in unrealized appreciation (depreciation) on investments' shown separately.",
        fixSubagentRaw: "Bifurcate the combined line on the face of the Statement of Operations: 'Net realized gain (loss) on investments' and 'Net change in unrealized appreciation (depreciation) on investments' shown separately.",
        fixVoiceNormalized: null,
        fixControllerEdited: null,
        evidence: { asc_reference: "ASC 946-220-45-3", xlsx_proof: "SOO!C26 = 61,200,000 ; SOO!C27 = 81,100,000 ; sum ties to SOO!C28 = 142,300,000", quoted_text: "Net realized and unrealized gain (loss) on investments $ 142,300,000" },
        merge_key: "Statement of Operations::Realized and unrealized gain/loss::Net realized and unrealized gain/loss::tie_out_break",
        finding_class: "tie_out_break",
        prior_review_recurrence: "RECURRING",
        evergreen_accepted: false,
        reconciler_pattern: null,
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "asc-matrices.md": "8.1.0" },
        state: "OPEN",
        disposition_notes: null,
        detail: "Same merge_key fired in FY2024 (prior F-014, state ACCEPTED). Escalated per prior-review-escalation.md."
      },
      {
        id: "F-004",
        subagent: "standards",
        layer: "L9",
        statement: "Notes to Financial Statements",
        section: "Fair value measurements",
        sortOrder: 20,
        location: { statement: "Notes to Financial Statements", page: 17, line_id: null, note_ref: "Note 4(b)", column: null, xlsx_cell: null },
        severity: { impact: "CRITICAL", confidence: "CERTAIN" },
        subagentRaw: "The Level 3 reconciliation roll-forward in Note 4(b) presents opening balance, purchases, and ending balance. ASC 820-10-50-2(c) requires opening balance, purchases, sales, settlements, issuances, transfers in/out, realized gain/loss, unrealized gain/loss, and ending balance. The still-held subset of realized/unrealized per -2(d) is also absent.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Expand the Level 3 roll-forward to include all eight required movement columns and the still-held subset disclosure. Verify the resulting ending balance ties to the Schedule of Investments Level 3 subtotal ($412.4M).",
        fixSubagentRaw: "Expand the Level 3 roll-forward to include all eight required movement columns and the still-held subset disclosure. Verify the resulting ending balance ties to the Schedule of Investments Level 3 subtotal ($412.4M).",
        evidence: { asc_reference: "ASC 820-10-50-2c", quoted_text: "Opening balance $ 387,000,000 / Purchases $ 25,400,000 / Ending balance $ 412,400,000" },
        merge_key: "Notes to Financial Statements::Fair value measurements::Note 4(b)::disclosure_gap",
        finding_class: "disclosure_gap",
        prior_review_recurrence: "NEW",
        evergreen_accepted: false,
        reconciler_pattern: "Pattern 06 — Level 3 Reconciliation Decomposition",
        reconciler_specificity_score: 24,
        constituent_findings: ["F-004a", "F-004b"],
        constituent_details: [
          {
            id: "F-004a",
            subagent: "mechanical",
            layer: "L2",
            severity: { impact: "CRITICAL", confidence: "CERTAIN" },
            subagentRaw: "Level 3 reconciliation ending balance ($412.4M) does not foot to the Schedule of Investments Level 3 subtotal ($408.9M); break $3.5M.",
            consumed_by_pattern: true
          },
          {
            id: "F-004b",
            subagent: "standards",
            layer: "L9",
            severity: { impact: "HIGH", confidence: "CERTAIN" },
            subagentRaw: "Significant unobservable inputs table at Note 4(c) lists valuation technique and range but omits the weighted-average column required by ASC 820-10-50-2(f).",
            consumed_by_pattern: true
          }
        ],
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "asc-matrices.md": "8.1.0", "cross-layer-patterns.md": "8.1.0" },
        state: "OPEN",
        detail: "Collapses Mechanical tie-out finding (L3 RF ending ≠ SOI L3 subtotal) and Standards 50-2(f) significant-inputs gap into one root cause."
      },
      {
        id: "F-005",
        subagent: "standards",
        layer: "L9",
        statement: "Schedule of Investments",
        section: "Concentration",
        sortOrder: 15,
        location: { statement: "Schedule of Investments", page: 12, line_id: "Other private equity investments (aggregated)", note_ref: null, column: null, xlsx_cell: null },
        severity: { impact: "HIGH", confidence: "CERTAIN" },
        subagentRaw: "The Schedule of Investments aggregates $158M (6.3% of NAV) under 'Other private equity investments' without name-level disclosure. ASC 946-210-50-6 requires name-level disclosure of any investment >5% of net assets.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Break out the constituent investments within the aggregated line by name; verify any single name >5% of NAV is separately disclosed.",
        fixSubagentRaw: "Break out the constituent investments within the aggregated line by name; verify any single name >5% of NAV is separately disclosed.",
        evidence: { asc_reference: "ASC 946-210-50-6", quoted_text: "Other private equity investments $ 158,000,000" },
        merge_key: "Schedule of Investments::Concentration::Other private equity investments (aggregated)::disclosure_gap",
        finding_class: "disclosure_gap",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "asc-matrices.md": "8.1.0" },
        state: "ACCEPTED",
        disposition_notes: "Confirmed with admin; will be broken out before final.",
        detail: null
      },
      {
        id: "F-006",
        subagent: "defense",
        layer: "L12",
        statement: "Notes to Financial Statements",
        section: "Organization",
        sortOrder: 25,
        location: { statement: "Notes to Financial Statements", page: 14, line_id: null, note_ref: "Note 1", column: null, xlsx_cell: null },
        severity: { impact: "MEDIUM", confidence: "CERTAIN" },
        subagentRaw: "The Organization note does not reference Cayman Private Funds Act registration. The Fund is a Cayman exempted limited partnership formed post-2020 — PFA registration disclosure is the standard expectation.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Add a sentence to the Organization note: 'The Fund is registered with the Cayman Islands Monetary Authority under the Private Funds Act (registration number [X]).' Verify the registration number from formation documents.",
        fixSubagentRaw: "Add a sentence to the Organization note: 'The Fund is registered with the Cayman Islands Monetary Authority under the Private Funds Act (registration number [X]).' Verify the registration number from formation documents.",
        evidence: { regulatory_citation: "CIMA:PFA", quoted_text: "AAA Coinvest Fund A LP (the 'Fund') is a Cayman Islands exempted limited partnership formed on [date]." },
        merge_key: "Notes to Financial Statements::Organization::Note 1::regulatory_gap",
        finding_class: "regulatory_gap",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "regulatory-corpus/CIMA.md": "8.1.0" },
        state: "OPEN",
        detail: null,
        comments: [
          { id: "c-seed1", author: "ashinde@apollo.com", ts: 1747497000000, text: "Confirmed PFA registration with formation counsel; registration number to come Monday. Will add the sentence then." }
        ],
        history: []
      },
      {
        id: "F-007",
        subagent: "defense",
        layer: "L14",
        statement: "Notes to Financial Statements",
        section: "Related party transactions",
        sortOrder: 35,
        location: { statement: "Notes to Financial Statements", page: 22, line_id: null, note_ref: "Note 8", column: null, xlsx_cell: null },
        severity: { impact: "HIGH", confidence: "PROBABLE" },
        subagentRaw: "The Related Party Transactions note discloses the General Partner and Investment Manager relationships but does not disclose the Fund's relationship to AAA Portfolio Operations LLC, which is named in the Schedule of Investments as the operating-services counterparty for two portfolio companies. The auditor will likely push back on this.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Confirm whether AAA Portfolio Operations LLC is an affiliate of the GP/Manager. If yes, expand Note 8 to disclose: nature of relationship, terms of services, period amount, and balance receivable/payable at period end.",
        fixSubagentRaw: "Confirm whether AAA Portfolio Operations LLC is an affiliate of the GP/Manager. If yes, expand Note 8 to disclose: nature of relationship, terms of services, period amount, and balance receivable/payable at period end.",
        evidence: { quoted_text: "The Fund has entered into a management agreement with the Investment Manager...", regulatory_citation: null },
        merge_key: "Notes to Financial Statements::Related party transactions::Note 8::audit_defense",
        finding_class: "audit_defense",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: {},
        state: "OPEN",
        detail: null
      },
      {
        id: "F-008",
        subagent: "defense",
        layer: "L12",
        statement: "Notes to Financial Statements",
        section: "Income taxes",
        sortOrder: 40,
        location: { statement: "Notes to Financial Statements", page: 25, line_id: null, note_ref: "Note 9", column: null, xlsx_cell: null },
        severity: { impact: "HIGH", confidence: "PROBABLE" },
        subagentRaw: "The Income Taxes note states the Fund has no uncertain tax positions. The Schedule of Investments shows non-US corporate investments. The note does not address PFIC treatment for US investors. If any non-US corporate investment qualifies as a PFIC, the disclosure regime under IRC §1297–1298 applies.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Confirm with tax counsel which non-US corporate investments qualify as PFICs. Add disclosure covering: (a) presence of PFIC investments, (b) treatment (mark-to-market under §1296 / QEF under §1295 / default §1291), (c) whether elections have been made on investors' behalf.",
        fixSubagentRaw: "Confirm with tax counsel which non-US corporate investments qualify as PFICs. Add disclosure covering: (a) presence of PFIC investments, (b) treatment (mark-to-market under §1296 / QEF under §1295 / default §1291), (c) whether elections have been made on investors' behalf.",
        evidence: { regulatory_citation: "IRS:PFIC", quoted_text: "The Fund has no uncertain tax positions as of the period end." },
        merge_key: "Notes to Financial Statements::Income taxes::Note 9::regulatory_gap",
        finding_class: "regulatory_gap",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "regulatory-corpus/IRS.md": "8.1.0" },
        state: "OPEN",
        detail: null
      },
      {
        id: "F-009",
        subagent: "standards",
        layer: "L9",
        statement: "Notes to Financial Statements",
        section: "Recently issued accounting standards",
        sortOrder: 60,
        location: { statement: "Notes to Financial Statements", page: 30, line_id: null, note_ref: "Note 13", column: null, xlsx_cell: null },
        severity: { impact: "MEDIUM", confidence: "PROBABLE" },
        subagentRaw: "The 'Recently issued accounting standards' note mentions ASU 2022-03 but does not address ASU 2023-09 (income tax disclosures, effective FY 2025+) — which may be applicable if the Fund has taxable blocker subsidiaries.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Confirm with tax team whether ASU 2023-09 applies (taxable blocker subsidiaries with rate reconciliation). If applicable, add the ASU 2023-09 effective-date and expected-effect disclosure to Note 13.",
        fixSubagentRaw: "Confirm with tax team whether ASU 2023-09 applies (taxable blocker subsidiaries with rate reconciliation). If applicable, add the ASU 2023-09 effective-date and expected-effect disclosure to Note 13.",
        evidence: { asc_reference: "ASC 105-10-65", quoted_text: "The Fund adopted ASU 2022-03 (Equity Securities with Contractual Sale Restrictions) effective January 1, 2024." },
        merge_key: "Notes to Financial Statements::Recently issued accounting standards::Note 13::disclosure_gap",
        finding_class: "disclosure_gap",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "asc-matrices.md": "8.1.0" },
        state: "OPEN",
        detail: null
      },
      {
        id: "F-010",
        subagent: "narrative",
        layer: "L3",
        statement: "Notes to Financial Statements",
        section: "Subsequent events",
        sortOrder: 65,
        location: { statement: "Notes to Financial Statements", page: 31, line_id: null, note_ref: "Note 14", column: null, xlsx_cell: null },
        severity: { impact: "MEDIUM", confidence: "CERTAIN" },
        subagentRaw: "The Subsequent Events note states events were evaluated through April 15, 2026. The draft is dated May 17, 2026 — the evaluation date precedes the draft date by over a month. Either the evaluation date is stale or the draft date is pre-dated.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Update the subsequent-events evaluation date to the expected issuance date. Re-evaluate events occurring between the prior date and the new date.",
        fixSubagentRaw: "Update the subsequent-events evaluation date to the expected issuance date. Re-evaluate events occurring between the prior date and the new date.",
        evidence: { asc_reference: "ASC 855-10-50-4", quoted_text: "The Fund has evaluated subsequent events through April 15, 2026." },
        merge_key: "Notes to Financial Statements::Subsequent events::Note 14::disclosure_gap",
        finding_class: "disclosure_gap",
        prior_review_recurrence: "REGRESSED",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "asc-matrices.md": "8.1.0" },
        state: "OPEN",
        detail: "Prior review F-008 (FY2024) was RESOLVED. Same merge_key now fires again — escalated."
      },
      {
        id: "F-011",
        subagent: "mechanical",
        layer: "L8",
        statement: "Schedule of Investments",
        section: "Level 3 designation",
        sortOrder: 14,
        location: { statement: "Schedule of Investments", page: 13, line_id: "Project Titan Holdings", note_ref: null, column: "Level", xlsx_cell: "SOI!K47" },
        severity: { impact: "CRITICAL", confidence: "PROBABLE" },
        subagentRaw: "Hidden workbook row at SOI!47 classifies Project Titan Holdings as Level 2. Visible row at SOI!46 (same investment) shows Level 3. The published FS shows Level 3. The hidden row may indicate either a working-paper override or an unresolved valuation question.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Resolve the Level classification with the valuation committee. Document the rationale in the VPM file. Hide the inactive row OR delete the row to remove the contradiction signal.",
        fixSubagentRaw: "Resolve the Level classification with the valuation committee. Document the rationale in the VPM file. Hide the inactive row OR delete the row to remove the contradiction signal.",
        evidence: { xlsx_proof: "SOI!K46 = 'Level 3' (visible) ; SOI!K47 = 'Level 2' (hidden, same investment)", quoted_text: "Project Titan Holdings — Level 3 — $ 87,400,000" },
        merge_key: "Schedule of Investments::Level 3 designation::Project Titan Holdings::forensic_ghost",
        finding_class: "forensic_ghost",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "vpm-security-mapping.md": "8.1.0" },
        state: "OPEN",
        detail: null
      },
      {
        id: "F-012",
        subagent: "comparative",
        layer: "L11",
        statement: "Cross-Statement",
        section: "Carried interest reconciliation",
        sortOrder: 5,
        location: { statement: "Cross-Statement", page: null, line_id: "Carried interest accrual", note_ref: null, column: null, xlsx_cell: null },
        severity: { impact: "HIGH", confidence: "CERTAIN" },
        subagentRaw: "AAA Coinvest Fund A LP records carried interest accrual of $34.2M on the Statement of Changes. The sibling AIV vehicle (AAA Coinvest Fund A AIV LP) FS records zero carried interest accrual. Per the LPA, the AIV applies a parallel waterfall — a proportional accrual is expected.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Reconcile the carried interest accrual between Fund A and Fund A AIV. Either correct one of them or document the timing/policy reason for the difference in both sets of FS.",
        fixSubagentRaw: "Reconcile the carried interest accrual between Fund A and Fund A AIV. Either correct one of them or document the timing/policy reason for the difference in both sets of FS.",
        evidence: { prior_text: "AIV FS Note 7: 'No carried interest has been allocated as of period end.'", quoted_text: "Carried interest accrual $ 34,200,000" },
        merge_key: "Cross-Statement::Carried interest reconciliation::Carried interest accrual::inter_entity_break",
        finding_class: "inter_entity_break",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: { "consolidation-decision-tree.md": "8.1.0" },
        state: "OPEN",
        detail: null
      },
      {
        id: "F-013",
        subagent: "narrative",
        layer: "L7",
        statement: "Notes to Financial Statements",
        section: "Significant accounting policies",
        sortOrder: 15,
        location: { statement: "Notes to Financial Statements", page: 15, line_id: null, note_ref: "Note 2", column: null, xlsx_cell: null },
        severity: { impact: "HIGH", confidence: "CERTAIN" },
        subagentRaw: "The Significant Accounting Policies note references 'the Fund's investments in AAA Coinvest Fund III portfolio companies' — AAA Coinvest Fund III is a different vehicle. This appears to be carried-over language from a prior draft of a different fund's FS.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Replace 'AAA Coinvest Fund III' with the correct entity name ('AAA Coinvest Fund A LP' or 'the Fund'). Scan the entire note set for additional cross-fund residue.",
        fixSubagentRaw: "Replace 'AAA Coinvest Fund III' with the correct entity name ('AAA Coinvest Fund A LP' or 'the Fund'). Scan the entire note set for additional cross-fund residue.",
        evidence: { quoted_text: "Investments are recorded at fair value, including the Fund's investments in AAA Coinvest Fund III portfolio companies." },
        merge_key: "Notes to Financial Statements::Significant accounting policies::Note 2::forensic_ghost",
        finding_class: "forensic_ghost",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: {},
        state: "OPEN",
        detail: null
      },
      {
        id: "F-014",
        subagent: "narrative",
        layer: "L3",
        statement: "Statement of Cash Flows",
        section: "Election-out narrative",
        sortOrder: 5,
        location: { statement: "Statement of Cash Flows", page: 6, line_id: null, note_ref: null, column: null, xlsx_cell: null },
        severity: { impact: "LOW", confidence: "POSSIBLE" },
        subagentRaw: "The Statement of Cash Flows election-out narrative is unusually brief — a single sentence noting the election under ASC 946-230-45-2. Some funds present a fuller justification covering each of the four scope criteria.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Consider expanding the narrative to enumerate the four scope criteria of ASC 946-230-45-2. Optional; current language is acceptable.",
        fixSubagentRaw: "Consider expanding the narrative to enumerate the four scope criteria of ASC 946-230-45-2. Optional; current language is acceptable.",
        evidence: { asc_reference: "ASC 946-230-45-2", quoted_text: "The Fund has elected to not present a Statement of Cash Flows under ASC 946-230-45-2." },
        merge_key: "Statement of Cash Flows::Election-out narrative::null::disclosure_gap",
        finding_class: "disclosure_gap",
        prior_review_recurrence: "EVERGREEN_ACCEPTED",
        evergreen_accepted: true,
        evergreen_acceptance_reason: "Auditor accepted the brief language in FY2023 and FY2024. Fund meets all four scope criteria; brevity is intentional.",
        evergreen_acceptance_date: "2024-05-15",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: {},
        state: "OPEN",
        detail: null
      },
      {
        id: "F-015",
        subagent: "narrative",
        layer: "L6",
        statement: "Notes to Financial Statements",
        section: "Cross-references",
        sortOrder: 50,
        location: { statement: "Notes to Financial Statements", page: 28, line_id: null, note_ref: "Note 11", column: null, xlsx_cell: null },
        severity: { impact: "MEDIUM", confidence: "CERTAIN" },
        subagentRaw: "Note 11 (Commitments and Contingencies) references 'as described in Note 12(b)'. Note 12 is the Financial Highlights note and does not have a sub-section (b). The reference is broken.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Locate the intended reference (likely Note 7 — Management Fees and Carried Interest sub-section b, or Note 8 — Related Party Transactions). Correct the reference.",
        fixSubagentRaw: "Locate the intended reference (likely Note 7 — Management Fees and Carried Interest sub-section b, or Note 8 — Related Party Transactions). Correct the reference.",
        evidence: { quoted_text: "The Fund is subject to indemnification obligations as described in Note 12(b)." },
        merge_key: "Notes to Financial Statements::Cross-references::Note 11::language_error",
        finding_class: "language_error",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: {},
        state: "RESOLVED",
        disposition_notes: "Fixed in Draft 1.2 working copy; will be in next reviewed draft.",
        detail: null
      },
      {
        id: "F-016",
        subagent: "narrative",
        layer: "L5",
        statement: "Financial Highlights",
        section: "Per-class ratios",
        sortOrder: 5,
        location: { statement: "Financial Highlights", page: 33, line_id: "Expense ratio", note_ref: null, column: "Class A", xlsx_cell: null },
        severity: { impact: "LOW", confidence: "CERTAIN" },
        subagentRaw: "Financial Highlights expense ratio for Class A is presented as 1.85 with no percent sign. All other ratios on the same page use percentage notation. Cosmetic inconsistency.",
        voiceNormalized: null,
        controllerEdited: null,
        fix: "Add the percent sign to the Class A expense ratio for typographic consistency.",
        fixSubagentRaw: "Add the percent sign to the Class A expense ratio for typographic consistency.",
        evidence: { quoted_text: "Class A expense ratio: 1.85" },
        merge_key: "Financial Highlights::Per-class ratios::Expense ratio::formatting",
        finding_class: "formatting",
        prior_review_recurrence: "NEW",
        subagent_version: "8.1.0",
        prompt_version: "v8.1.0",
        reference_versions: {},
        state: "DISCARDED",
        disposition_notes: "Trivial. Preparer to fix without tracking.",
        detail: null
      }
    ],

    reconciler_decisions: [
      {
        cluster_id: "C-001",
        statement: "Notes to Financial Statements",
        section: "Fair value measurements",
        candidate_patterns: [
          { pattern: "Pattern 06 — Level 3 Reconciliation Decomposition", triggers_met: 3, severity_floor: "CRITICAL", statement_scope: "single", specificity_score: 24, winner: true },
          { pattern: "Pattern 12 — Comparative Movement With Standards Trigger", triggers_met: 2, severity_floor: "MEDIUM", statement_scope: "cross-statement", specificity_score: 4, winner: false }
        ],
        consumed_finding_ids: ["F-004a", "F-004b"],
        root_cause_id: "F-004"
      }
    ]
  }
};
